
# Define a dictionary of explicit terms and their medical counterparts
explicit_medical_terms = {
    "penis": "",
    "vagina": "",
    "breast": "",
    "testicles": "",
    "uterus": "",
    "rectum": "",
    "labia": "",
    "clitoris": "",
    "genitals": "",
    "private parts": "",
    "sexual organ": "",
    "groin": "",
    "anatomy": "",
    "copulate": "",
    "intimate": "",
    "libido": "",
    "erogenous zones": "",
    "procreation": "",
    "phallus": "",
    "ovaries": "",
    "pubic hair": "",
    "erectile tissue": "",
    "fertilization": "",
    "sexuality": "",
    "virginity": "",
    "liberator": "",
    "stimulate": "",
    "prophylactic": "",
    "erectile dysfunction": "",
    "puberty": "",
    "contraception": "",
    "kama sutra": "",
    "foreplay": "",
    "ejaculation": "",
    "fetish": "",
    "bisexual": "",
    "transgender": "",
    "sexually transmitted infection": "",
    "liberated": "",
    "sex therapy": "",
    "erotic": "",
    "androgynous": "",
    "cunnilingus": "",
    "fellatio": "",
    "sensual": "",
    "aphrodisiac": "",
    "monogamy": "",
    "polyamory": "",
    "tantra": "",
    "libidinous": "",
    "philter": "",
    "liberal": "",
    "libertine": "",
    "sodomy": "",
    "vanilla": "",
    "kinky": "",
    "safeword": "",
    "orgasm": "",
    "fornicate": "",
    "voyeurism": "",
    "exhibitionism": "",
    "libidinal": "",
    "copulation": "",
    "hedonism": "",
    "perversion": "",
    "sexologist": "",
    "coitus": "",
    "censorship": "",
    "liberalize": "",
    "liberator": "",
    "desire": "",
    "passion": "",
    "seduction": "",
    "intimacy": "",
    "arousal": "",
    "kiss": "",
    "touch": "",
    "fantasy": "",
    "pleasure": "",
    "ecstasy": "",
    "liberating": "",
    "attraction": "",
    "infatuation": "",
    "nudity": "",
    "sensual massage": "",
    "sexual tension": "",
    "sensuality": "",
    "forbidden": "",
    "lust": "",
    "erotic literature": "",
    "seductive": "",
    "liberated": "",
    "pleasure principle": "",
    "libidinal energy": "",
    "sexual exploration": "",
    "sexual identity": "",
    "sexual fluidity": "",
    "sexual orientation": "",
    "taboo": "",
    "sensory play": "",
    "erotic art": "",
    "sensual music": "",
    "passionate kiss": "",
    "liberating experience": "",
    "erotic fantasy": "",
    "sexual chemistry": "",
    "sensual pleasure": "",
    "sensual dance": "",
    "libertarian views on sexuality": "",
    "sexual empowerment": "",
    "liberating clothing": "",
    "consensual sex": "",
    "sexual revolution": "",
    "sexual expression": "",
    "sexual satisfaction": "",
    "liberated mindset": "",
    "erotic poetry": "",
    "sexual autonomy": "",
    "liberal sexual education": "",
    "pleasure-seeking": "",
    "sexual diversity": "",
    "liberated lifestyle": "",
    "sexual confidence": "",
    "libidinal instincts": "",
    "sex-positive": "",
    "sexual attraction": "",
    "liberated relationship": "",
    "sensual fragrance": "",
    "sexual wellness": "",
    "libidinous artwork": "",
    "sexual liberation movement": "",
    "libertine lifestyle": "",
    "sexual empowerment": "",
    "passionate": "",
    "seductive": "",
    "lustful": "",
    "provocative": "",
    "sultry": "",
    "arousing": "",
    "intoxicating": "",
    "voluptuous": "",
    "sensuous": "",
    "provocative": "",
    "flirtation": "",
    "foreplay": "",
    "teasing": "",
    "enticing": "",
    "captivating": "",
    "intense": "",
    "intertwine": "",
    "intoxicate": "",
    "ecstasy": "",
    "ravish": "",
    "pleasurable": "",
    "passion": "",
    "devour": "",
    "satisfy": "",
    "stimulation": "",
    "orgasmic": "",
    "ecstatic": "",
    "thrilling": "",
    "enchanting": "",
    "captivate": "",
    "bewitching": "",
    "enrapture": "",
    "allure": "",
    "irresistible": "",
    "attraction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "temptation": "",
    "seducing": "",
    "enthralling": "",
    "intoxicating": "",
    "mesmerizing": "",
    "spellbinding": "",
    "enveloping": "",
    "enrapturing": "",
    "pleasure": "",
    "delight": "",
    "rapture": "",
    "blissful": "",
    "exhilarating": "",
    "intimate": "",
    "passion": "",
    "sensual": "",
    "lust": "",
    "romance": "",
    "desire": "",
    "intensity": "",
    "infatuate": "",
    "enjoyment": "",
    "hedonistic": "",
    "libidinous": "",
    "voluptuary": "",
    "uninhibited": "",
    "carnal": "",
    "lewd": "",
    "titillating": "",
    "amorous": "",
    "lascivious": "",
    "sensory": "",
    "pleasuring": "",
    "unrestrained": "",
    "provocative": "",
    "enticing": "",
    "captivating": "",
    "intoxicating": "",
    "voluptuous": "",
    "sensuous": "",
    "provocative": "",
    "flirtation": "",
    "foreplay": "",
    "teasing": "",
    "enticing": "",
    "captivating": "",
    "intense": "",
    "intertwine": "",
    "intoxicate": "",
    "ecstasy": "",
    "ravish": "",
    "pleasurable": "",
    "passion": "",
    "devour": "",
    "satisfy": "",
    "stimulation": "",
    "orgasmic": "",
    "ecstatic": "",
    "thrilling": "",
    "enchanting": "",
    "captivate": "",
    "bewitching": "",
    "enrapture": "",
    "allure": "",
    "irresistible": "",
    "attraction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "temptation": "",
    "seducing": "",
    "enthralling": "",
    "intoxicating": "",
    "mesmerizing": "",
    "spellbinding": "",
    "enveloping": "",
    "enrapturing": "",
    "pleasure": "",
    "delight": "",
    "rapture": "",
    "blissful": "",
    "exhilarating": "",
    "intimate": "",
    "passion": "",
    "sensual": "",
    "lust": "",
    "romance": "",
    "desire": "",
    "intensity": "",
    "infatuate": "",
    "enjoyment": "",
    "hedonistic": "",
    "libidinous": "",
    "voluptuary": "",
    "uninhibited": "",
    "carnal": "",
    "lewd": "",
    "titillating": "",
    "amorous": "",
    "lascivious": "",
    "sensory": "",
    "pleasuring": "",
    "unrestrained": "",
    "provocative": "",
    "enticing": "",
    "captivating": "",
    "intoxicating": "",
    "voluptuous": "",
    "sensuous": "",
    "provocative": "",
    "flirtation": "",
    "foreplay": "",
    "teasing": "",
    "enticing": "",
    "captivating": "",
    "intense": "",
    "intertwine": "",
    "intoxicate": "",
    "ecstasy": "",
    "ravish": "",
    "pleasurable": "",
    "passion": "",
    "devour": "",
    "satisfy": "",
    "stimulation": "",
    "orgasmic": "",
    "ecstatic": "",
    "thrilling": "",
    "enchanting": "",
    "captivate": "",
    "bewitching": "",
    "enrapture": "",
    "allure": "",
    "irresistible": "",
    "attraction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "temptation": "",
    "seducing": "",
    "enthralling": "",
    "intoxicating": "",
    "mesmerizing": "",
    "spellbinding": "",
    "enveloping": "",
    "enrapturing": "",
    "pleasure": "",
    "delight": "",
    "rapture": "",
    "blissful": "",
    "exhilarating": "",
    "intimate": "",
    "passion": "",
    "sensual": "",
    "lust": "",
    "romance": "",
    "desire": "",
    "intensity": "",
    "infatuate": "",
    "enjoyment": "",
    "hedonistic": "",
    "libidinous": "",
    "voluptuary": "",
    "uninhibited": "",
    "carnal": "",
    "lewd": "",
    "titillating": "",
    "amorous": "",
    "lascivious": "",
    "sensory": "",
    "pleasuring": "",
    "unrestrained": "",
    "provocative": "",
    "enticing": "",
    "captivating": "",
    "intoxicating": "",
    "voluptuous": "",
    "sensuous": "",
    "provocative": "",
    "flirtation": "",
    "foreplay": "",
    "teasing": "",
    "enticing": "",
    "captivating": "",
    "intense": "",
    "intertwine": "",
    "intoxicate": "",
    "ecstasy": "",
    "ravish": "",
    "pleasurable": "",
    "passion": "",
    "devour": "",
    "satisfy": "",
    "stimulation": "",
    "orgasmic": "",
    "ecstatic": "",
    "thrilling": "",
    "enchanting": "",
    "captivate": "",
    "bewitching": "",
    "enrapture": "",
    "allure": "",
    "irresistible": "",
    "attraction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "temptation": "",
    "seducing": "",
    "enthralling": "",
    "intoxicating": "",
    "mesmerizing": "",
    "spellbinding": "",
    "enveloping": "",
    "enrapturing": "",
    "pleasure": "",
    "delight": "",
    "rapture": "",
    "blissful": "",
    "exhilarating": "",
    "intimate": "",
    "passion": "",
    "sensual": "",
    "lust": "",
    "romance": "",
    "desire": "",
    "intensity": "",
    "infatuate": "",
    "enjoyment": "",
    "hedonistic": "",
    "libidinous": "",
    "voluptuary": "",
    "uninhibited": "",
    "carnal": "",
    "lewd": "",
    "titillating": "",
    "amorous": "",
    "lascivious": "",
    "sensory": "",
    "pleasuring": "",
    "unrestrained": "",
    "provocative": "",
    "enticing": "",
    "captivating": "",
    "intoxicating": "",
    "voluptuous": "",
    "sensuous": "",
    "provocative": "",
    "flirtation": "",
    "foreplay": "",
    "teasing": "",
    "enticing": "",
    "captivating": "",
    "intense": "",
    "intertwine": "",
    "intoxicate": "",
    "ecstasy": "",
    "ravish": "",
    "pleasurable": "",
    "passion": "",
    "devour": "",
    "satisfy": "",
    "stimulation": "",
    "orgasmic": "",
    "ecstatic": "",
    "thrilling": "",
    "enchanting": "",
    "captivate": "",
    "bewitching": "",
    "enrapture": "",
    "allure": "",
    "irresistible": "",
    "attraction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "infatuation": "",
    "yearning": "",
    "seduction": "",
    "temptation": "",
    "seducing": "",
    "enthralling": "",
    "intoxicating": "",
    "mesmerizing": "",
    "spellbinding": "",
    "enveloping": "",
    "enrapturing": "",
    "pleasure": "",
    "delight": "",
    "rapture": "",
    "blissful": "",
    "exhilarating": "",
    "intimate": "",
    "passion": "",
    "sensual": "",
    "lust": "",
    "romance": "",
    "desire": "",
    "intensity": "",
    "infatuate": "",
    "enjoyment": "",
    "hedonistic": "",
    "libidinous": "",
    "voluptuary": "",
    "uninhibited": "",
    "carnal": "",
    "lewd": "",
    "titillating": "",
    "amorous": "",
    "lascivious": "",
    "sensory": "",
    "pleasuring": "",
    "unrestrained": "",
    "provocative": "",
    "enticing": "",
    "captivating": "",
    "intoxicating": "",
    "voluptuous": "",
    "sensuous": "",
    "provocative": "",
    "flirtation": "",
    "foreplay": "",
    "teasing": "",
    "enticing": "",
    "captivating": "",
    "intense": "",
    "intertwine": "",
    "intoxicate": "",
    "ecstasy": "",
    "ravish": "",
    "pleasurable": "",
    "passion": "",
    "devour": "",
    "satisfy": "",
    "stimulation": "",
    "orgasmic": "",
    "ecstatic": "",
    "thrilling": "",
    "enchanting": "",
    "captivate": "",
    "bewitching": "",
    "enrapture": "",
    "allure": "",
    "irresistible": "",
    "attraction": "",
    "infatuation": "",
    "yearning": "",
}