
# Define a dictionary of explicit terms and their medical counterparts
explicit_medical_terms = {
    "Ableism":"",
    "Abortifacient":"",
    "Abortion":"",
    "Abortion funds":"",
    "Abortion pill":"",
    "Abstinence":"",
    "Abstinence-only programs":"",
    "Acetaminophen":"",
    "Acquaintance rape":"",
    "Acquired immune deficiency syndrome":"",
    "Adolescence":"",
    "Adrenarche":"",
    "Affordable Care Act":"",
    "Afterbirth":"",
    "Age of consent":"",
    "Agency":"",
    "Agender":"",
    "AIDS":"",
    "AIS":"",
    "Ally":"",
    "Alternative insemination":"",
    "Amenorrhea":"",
    "Amniocentesis":"",
    "Amniotic fluid":"",
    "Anal beads":"",
    "Anal fissure":"",
    "Anal sex":"",
    "Androgen insensitivity syndrome":"",
    "Androgens":"",
    "Androgynous":"",
    "Andropause":"",
    "Androphobia":"",
    "Anesthesia":"",
    "Anilingus":"",
    "Anorexia":"",
    "Anorgasmia":"",
    "Anti-choice":"",
    "Antiandrogen":"",
    "Antibiotics":"",
    "Antibody":"",
    "Antiretroviral":"",
    "Anus":"",
    "Aphrodisiac":"",
    "Areola":"",
    "Aroused":"",
    "Artificial insemination":"",
    "Asexual":"",
    "Aspiration abortion":"",
    "Aspirin":"",
    "Assigned female at birth":"",
    "Assigned male at birth":"",
    "Asymptomatic":"",
    "Atrophic vaginitis":"",
    "Autoerotic":"",
    "Autoerotic asphyxiation":"",
    "Backup birth control":"",
    "Bacterial vaginosis":"",
    "Balanitis":"",
    "Barrier methods of birth control":"",
    "Barriers for safer sex":"",
    "Bartholin’s glands":"",
    "Basal body temperature method":"",
    "BDSM":"",
    "Benign":"",
    "Bi erasure":"",
    "Bigender":"",
    "Bilateral mastectomy":"",
    "Binarism":"",
    "Binder":"",
    "Biopsy":"",
    "Biphobia":"",
    "Birth canal":"",
    "Birth center":"",
    "Birth control":"",
    "Birth defect":"",
    "Bisexual":"",
    "Bladder":"",
    "Blastocyst":"",
    "Blue balls":"",
    "Body autonomy":"",
    "Body diversity":"",
    "Body fluids":"",
    "Body image":"",
    "Boner":"",
    "Bottom surgery":"",
    "Breastfeeding":"",
    "Breasts":"",
    "Bulbourethral glands":"",
    "Butch":"",
    "Butt plug":"",
    "Bv":"",
    "C-section":"",
    "Calendar method":"",
    "Cancer":"",
    "Candida":"",
    "Cap":"",
    "Castration":"",
    "Casual sex":"",
    "Celibacy":"",
    "Censorship":"",
    "Cervical cap":"",
    "Cervical dilator":"",
    "Cervical mucus":"",
    "Cervical mucus method":"",
    "Cervicitis":"",
    "Cervix":"",
    "Cesarean section":"",
    "Ceterosexual":"",
    "Chancre":"",
    "Chancroid":"",
    "Chemical castration":"",
    "Chest binding":"",
    "Chest surgery":"",
    "Chestfeeding":"",
    "Child pornography":"",
    "Chlamydia":"",
    "Chorionic villus sampling":"",
    "Chosen family":"",
    "Chosen name":"",
    "Chromosomes":"",
    "Circumcision":"",
    "Cis man":"",
    "Cis woman ":"",
    "Cisgender":"",
    "Cisnormativity":"",
    "Cissexism":"",
    "Climax":"",
    "Clinician":"",
    "Clit":"",
    "Clitoral hood":"",
    "Clitoridectomy":"",
    "Clitoris":"",
    "Closet":"",
    "CMV ":"",
    "Coercion":"",
    "Cognitive behavioral therapy":"",
    "Coitophobia":"",
    "Coitus":"",
    "Colostrum":"",
    "Colposcope":"",
    "Combination pill":"",
    "Combined hormone contraceptives":"",
    "Combined oral contraceptives":"",
    "Coming out":"",
    "Complete miscarriage":"",
    "Comprehensive sex education":"",
    "Comstock Act":"",
    "Conception":"",
    "Congenital syphilis":"",
    "Consent":"",
    "Contraception/contraceptive":"",
    "Contraceptive creams and jellies":"",
    "Contraceptive film":"",
    "Contraceptive foam":"",
    "Contraceptive suppository":"",
    "Contraction":"",
    "Copay":"",
    "Copulation":"",
    "Corpus cavernosa":"",
    "Corpus luteum":"",
    "Corpus spongiosum":"",
    "Couvade syndrome":"",
    "Cowper’s glands":"",
    "Cremaster":"",
    "Cremaster reflex":"",
    "Cross-dressing":"",
    "Crura":"",
    "Cryotherapy":"",
    "Cryptorchidism":"",
    "CT scan":"",
    "Cum":"",
    "Cunnilingus":"",
    "Curette":"",
    "Cushing syndrome":"",
    "CVS":"",
    "Cybersex":"",
    "Cyberstalking":"",
    "Cystitis":"",
    "Cytomegalovirus":"",
    "Date rape":"",
    "Deadnaming":"",
    "Deductible":"",
    "Demisexual":"",
    "Dental dam":"",
    "Depo-provera":"",
    "Depotmedroxyprogesterone acetate":"",
    "Desire phase":"",
    "Diaphragm":"",
    "Dilators":"",
    "Dildo":"",
    "DMPA":"",
    "Domestic partnership":"",
    "Donor insemination":"",
    "Double standard":"",
    "Douche":"",
    "Doula":"",
    "Down syndrome":"",
    "Drag":"",
    "Drag king":"",
    "Drag queen":"",
    "Dry days":"",
    "Dry humping":"",
    "Dry orgasm":"",
    "Dysmenorrhea":"",
    "Dyspareunia":"",
    "Dysplasia":"",
    "Eclampsia":"",
    "Ectopic pregnancy":"",
    "Edging":"",
    "Egg":"",
    "Eisenstadt v. Baird":"",
    "Ejaculation":"",
    "Ejaculatory inevitability":"",
    "Embryo":"",
    "Emergency contraception":"",
    "Enby":"",
    "Endometriosis":"",
    "Endometrium":"",
    "Endosex":"",
    "Endosexism":"",
    "Enovid":"",
    "Epididymis":"",
    "Epididymitis":"",
    "Epidural":"",
    "Episiotomy":"",
    "Epithelium":"",
    "Equal Rights Amendment":"",
    "Equality":"",
    "Equity":"",
    "ERA":"",
    "Erect anatomy":"",
    "Erectile dysfunction":"",
    "Erectile tissue":"",
    "Erection":"",
    "Erogenous zone":"",
    "Erotic":"",
    "Erotica":"",
    "Erotophobia":"",
    "Escort":"",
    "Estradiol":"",
    "Estrogen":"",
    "Ethnicity":"",
    "Eugenics":"",
    "Eunuch":"",
    "Euphemism":"",
    "Excitement":"",
    "Exhibitionists":"",
    "External sex and reproductive organs":"",
    "Extramarital sex":"",
    "Feminine":"",
    "Feminism":"",
    "Femme":"",
    "Fertile days":"",
    "Fertility":"",
    "Fertility awareness-based methods":"",
    "Fertility cycle":"",
    "Fertility rate":"",
    "Fertilization":"",
    "Fetal alcohol spectrum disorders":"",
    "Fetishize":"",
    "Fetus":"",
    "Fibroid":"",
    "Finger cot":"",
    "First trimester":"",
    "Fisting":"",
    "Flashing":"",
    "Follicle":"",
    "Follicle stimulating hormone":"",
    "Fondling":"",
    "Fordyce spots":"",
    "Foreplay":"",
    "Foreskin":"",
    "Formula":"",
    "Fornication":"",
    "Frenulum":"",
    "Front hole":"",
    "Frottage":"",
    "FSH":"",
    "Ftm":"",
    "G spot":"",
    "Gaff":"",
    "Gamete":"",
    "Gamete intrafallopian tube transfer":"",
    "Gang rape":"",
    "Gaslighting":"",
    "Gay":"",
    "Gay bashing":"",
    "Gay liberation movement":"",
    "Gender":"",
    "Gender affirming care":"",
    "Gender affirming surgery":"",
    "Gender assignment":"",
    "Gender binary":"",
    "Gender conforming":"",
    "Gender dysphoria":"",
    "Gender euphoria":"",
    "Gender expression":"",
    "Gender fluidity ":"",
    "Gender history":"",
    "Gender identity":"",
    "Gender journey":"",
    "Gender marker ":"",
    "Gender modality":"",
    "Gender nonbinary":"",
    "Gender nonconforming":"",
    "Gender normative":"",
    "Gender norms":"",
    "Gender pronouns":"",
    "Gender roles":"",
    "Gender scripting":"",
    "Gender stereotype":"",
    "Gender-affirming hormone therapy":"",
    "Genderqueer":"",
    "Genes":"",
    "Genital herpes":"",
    "Genital mutilation":"",
    "Genital reconstruction surgery":"",
    "Genital warts":"",
    "Genitals":"",
    "Genophobia":"",
    "Gestation":"",
    "Gestational duration":"",
    "GIFT":"",
    "Gigolo":"",
    "Girldick":"",
    "Glans":"",
    "Gloves":"",
    "Gonadotropins":"",
    "Gonads":"",
    "Gonorrhea":"",
    "GRS":"",
    "Gräfenburg spot":"",
    "Guiche":"",
    "Gymnophobia":"",
    "Gynecologist":"",
    "Gynecology":"",
    "Gynecomastia":"",
    "Gynophobia":"",
    "Hand job":"",
    "Harness":"",
    "HBV":"",
    "Health care provider":"",
    "Health coverage":"",
    "Health insurance":"",
    "Heavy petting":"",
    "Hedonism":"",
    "Hello":"",
    "Hola":"",
    "Hemorrhoid":"",
    "Herpes":"",
    "Heteronormativity":"",
    "Heterosexism":"",
    "Heterosexual":"",
    "High-risk pregnancy":"",
    "HIV":"",
    "Homophobia":"",
    "Homosexual":"",
    "Hormonal contraceptives":"",
    "Hormone therapy":"",
    "Hormones":"",
    "Horny":"",
    "Hyde Amendment":"",
    "Hymen":"",
    "Hyperfemininity":"",
    "Hypermasculinity":"",
    "Hypersexual":"",
    "Hyposexual":"",
    "Hypothalamus":"",
    "Hysterectomy":"",
    "Hysteroscope":"",
    "Ibuprofen":"",
    "Immune system":"",
    "Implanon":"",
    "Implant":"",
    "Implantation":"",
    "Implantation bleeding":"",
    "Impotence":"",
    "In vitro fertilization: IVF":"",
    "In-clinic abortion":"",
    "In-network":"",
    "Incest":"",
    "Inclusive language":"",
    "Incomplete abortion":"",
    "Incontinence":"",
    "Indecent exposure":"",
    "Individual racism":"",
    "Induced abortion":"",
    "Induced menopause":"",
    "Inevitable miscarriage":"",
    "Infant mortality rate":"",
    "Infatuation":"",
    "Infertility":"",
    "Infibulation":"",
    "Infidelity":"",
    "Inhibited sexual arousal":"",
    "Inner lips":"",
    "Insemination":"",
    "Institutional racism":"",
    "Intact penis":"",
    "Intercourse":"",
    "Internal condom":"",
    "Internal sex":"",
    "Internalized homophobia":"",
    "Intersex":"",
    "Intimacy":"",
    "Jaundice":"",
    "Jealousy":"",
    "Jock itch":"",
    "Kegel exercises":"",
    "Kink, kinky":"",
    "Kinsey scale":"",
    "Klinefelter’s syndrome":"",
    "Labia":"",
    "Labia majora":"",
    "Labia minora":"",
    "Labor":"",
    "Lactational amenorrhea method LAM":"",
    "Lactobacillus":"",
    "LAM lactational amenorrhea method":"",
    "Lambskin":"",
    "Laminaria":"",
    "Laparoscope":"",
    "Laparoscopy":"",
    "Laparoscopy":"",
    "Laparotomy":"",
    "LEEP":"",
    "Legal disclaimer":"",
    "Legal Disclaimer":"",
    "Lesbian":"",
    "Leukorrhea":"",
    "Levonorgestrel":"",
    "LGBTQ+":"",
    "LH luteinizing hormone":"",
    "Libido":"",
    "Limbic system":"",
    "Limerence":"",
    "Lobes":"",
    "Love":"",
    "Low birth weight":"",
    "Lube lubricant":"",
    "Lumpectomy":"",
    "Lust":"",
    "Luteinizing hormone LH":"",
    "Male":"",
    "Male menopause":"",
    "Male-to-female trans":"",
    "Mammary glands":"",
    "Mammogram":"",
    "Manual vacuum aspiration":"",
    "Margaret Sanger":"",
    "Marital rape":"",
    "Marriage":"",
    "Masculine":"",
    "Mastectomy":"",
    "Mastitis":"",
    "Masturbation":"",
    "Maternal mortality":"",
    "Mayer-Rokitansky-Küster-Hauser":"",
    "Medication abortion":"",
    "Menarche":"",
    "Menopause":"",
    "Menorrhagia":"",
    "Menses":"",
    "Menstrual cup":"",
    "Menstrual cycle":"",
    "Menstrual flow":"",
    "Menstrual synchrony":"",
    "Menstruation":"",
    "Merkin":"",
    "Metastasize":"",
    "Method effectiveness":"",
    "Metoidioplasty":"",
    "Micropenis":"",
    "Midwife":"",
    "Mifepristone":"",
    "Mini-laparotomy":"",
    "Mini-pills":"",
    "Miscarriage":"",
    "Misgender":"",
    "Misogynoir":"",
    "Misogyny":"",
    "Misoprostol":"",
    "Missed abortion":"",
    "Missionary position":"",
    "Mittelschmerz":"",
    "Molar pregnancy":"",
    "Molluscum contagiosum":"",
    "Monogamy":"",
    "Mons veneris":"",
    "Mooning":"",
    "Morning sickness":"",
    "Morning wood":"",
    "Morning-after pill":"",
    "Morula":"",
    "MRI":"",
    "MTF":"",
    "Mucus method":"",
    "Muffing":"",
    "Multigender":"",
    "Multiparous":"",
    "Multiple marker screening":"",
    "Multiple orgasms":"",
    "Mutual masturbation":"",
    "Ménage à trois":"",
    "Naproxen":"",
    "Natural family planning":"",
    "Necrophilia":"",
    "Negative result":"",
    "Neonatal":"",
    "Neopronouns":"",
    "Neurula":"",
    "Nipple":"",
    "Nocturnal emission":"",
    "Nocturnal orgasm":"",
    "Nocturnal penile tumescence":"",
    "Non-op":"",
    "Nonbinary":"",
    "Nonoxynol-9":"",
    "Norgestrel":"",
    "Norplant":"",
    "NPT":"",
    "Nuchal translucency test":"",
    "Nulliparous":"",
    "Nurse practitioner":"",
    "Nurse-midwife":"",
    "NuvaRing":"",
    "Obamacare":"",
    "Obscenity":"",
    "Obstetrician":"",
    "One-night stand":"",
    "Oocyte":"",
    "Oophorectomy":"",
    "Open enrollment":"",
    "Open relationship":"",
    "Oppression":"",
    "Oral contraceptive":"",
    "Oral herpes":"",
    "Oral sex":"",
    "Orchiectomy":"",
    "Orchitis":"",
    "Orgasm":"",
    "Orgy":"",
    "Osteoporosis":"",
    "Out":"",
    "Out-of-network":"",
    "Outer lips":"",
    "Outercourse":"",
    "Outing":"",
    "Ovarian cyst":"",
    "Ovaries":"",
    "Over-the-counter":"",
    "Over-the-counter pain medicine":"",
    "Oviduct":"",
    "Ovulation":"",
    "Pack-and-play":"",
    "Packer":"",
    "Packing":"",
    "Pangender":"",
    "Pansexual":"",
    "Pap smear":"",
    "Pap test":"",
    "Paragard":"",
    "Paraphilia":"",
    "Parental consent":"",
    "Parous":"",
    "Parturition":"",
    "Passing":"",
    "Passing privilege":"",
    "Patriarchy":"",
    "Pause-and-squeeze method":"",
    "Pearl necklace":"",
    "Pearly pink papules":"",
    "Pelvic exam":"",
    "Pelvic floor muscles":"",
    "Pelvic inflammatory disease":"",
    "Pelvic tuberculosis":"",
    "Penectomy":"",
    "Penetration":"",
    "Penis":"",
    "PEP":"",
    "Perfect use":"",
    "Performance anxiety":"",
    "Perimenopause":"",
    "Perinatal":"",
    "Perineum":"",
    "Period":"",
    "Petting":"",
    "Peyronie’s disease":"",
    "Phallic":"",
    "Phallophobia":"",
    "Phalloplasty":"",
    "Pheromones":"",
    "Phimosis":"",
    "Phone sex":"",
    "Physician assistant":"",
    "PID":"",
    "Pill, the":"",
    "Pimp":"",
    "Pitching a tent":"",
    "Pituitary gland":"",
    "Placenta":"",
    "Plan B":"",
    "Plastics":"",
    "Plateau":"",
    "Platonic":"",
    "PMS":"",
    "Point of no return":"",
    "Polyamory":"",
    "Polycystic ovary syndrome":"",
    "Polygamy":"",
    "Polyps":"",
    "Pornography":"",
    "Positive result":"",
    "Post-exposure prophylaxis":"",
    "Post-ovulation method":"",
    "Postpartum":"",
    "Postpartum depression":"",
    "Postpartum psychosis":"",
    "Pre-cum":"",
    "Pre-eclampsia":"",
    "Pre-ejaculate":"",
    "Pre-embryo":"",
    "Pre-exposure prophylaxis":"",
    "Pregnancy":"",
    "Premarital sex":"",
    "Premature delivery":"",
    "Premature ejaculation":"",
    "PMDD":"",
    "PMS":"",
    "Premium":"",
    "Prenatal vitamins":"",
    "PrEP":"",
    "Prepuce":"",
    "Priapism":"",
    "Primary sex characteristics":"",
    "Primary syphilis":"",
    "Privilege":"",
    "Pro-choice":"",
    "Procreative sex":"",
    "Progesterone":"",
    "Progestin":"",
    "Prolapsed uterus":"",
    "Pronouns":"",
    "Prophylactic":"",
    "Prostate":"",
    "Prostatitis":"",
    "Prostitute":"",
    "Prostitution":"",
    "Puberty":"",
    "Pubic hair":"",
    "Pubic lice":"",
    "Pulling out":"",
    "Queef":"",
    "Queer":"",
    "Questioning":"",
    "Quickening":"",
    "Race":"",
    "Racism":"",
    "Rape":"",
    "Rectovaginal exam":"",
    "Rectum":"",
    "Refractory period":"",
    "Reproductive cell":"",
    "Reproductive Justice":"",
    "Reproductive organs":"",
    "Resolution":"",
    "Retrograde ejaculation":"",
    "Rh factor":"",
    "Rhythm method":"",
    "Right-to-life":"",
    "Rimming (rim job)":"",
    "Roe v. Wade":"",
    "Role-play":"",
    "Romantic":"",
    "Romantic attraction":"",
    "Romantic orientation":"",
    "RU-486":"",
    "S&M (sadomasochism)":"",
    "Sadomasochism":"",
    "Safe word":"",
    "Safer sex":"",
    "Sanitary pad":"",
    "Scabies":"",
    "Scrotum":"",
    "Second trimester":"",
    "Secondary sex characteristics":"",
    "Secondary syphilis":"",
    "Semen":"",
    "Seminal fluid":"",
    "Seminal vesicle":"",
    "Seminiferous tubules":"",
    "Septic abortion":"",
    "Sex":"",
    "Sex addiction":"",
    "Sex assignment":"",
    "Sex cell":"",
    "Sex drive":"",
    "Sex education":"",
    "Sex flush":"",
    "Sex positive":"",
    "Sex selection":"",
    "Sex therapy":"",
    "Sex work":"",
    "Sex-negative":"",
    "Sexism":"",
    "Sexology":"",
    "Sexophobia":"",
    "Sexting":"",
    "Sexual abuse":"",
    "Sexual arousal":"",
    "Sexual assault":"",
    "Sexual dysfunction":"",
    "Sexual fluids":"",
    "Sexual harassment":"",
    "Sexual health":"",
    "Sexual identity":"",
    "Sexual intercourse":"",
    "Sexual minority":"",
    "Sexual norms":"",
    "Sexual orientation":"",
    "Sexual preference":"",
    "Sexual response cycle":"",
    "Sexual revolution":"",
    "Sexuality":"",
    "Sexually transmitted disease":"",
    "Sexually transmitted infection":"",
    "Shaft":"",
    "Sheer glyde dam":"",
    "Sixty-nine / 69":"",
    "Skene’s glands":"",
    "Skoliosexual / scoliosexual":"",
    "Slut":"",
    "Slut shame":"",
    "Smegma":"",
    "Social construct":"",
    "Sodomy":"",
    "Sonogram":"",
    "Speculum":"",
    "Sperm":"",
    "Spermarche":"",
    "Spermatogenesis":"",
    "Spermicides":"",
    "Spina bifida":"",
    "Spontaneous abortion":"",
    "Spontaneous erection":"",
    "Spotting":"",
    "Spouse":"",
    "Squirting":"",
    "Stalking":"",
    "Standard days method":"",
    "Statutory rape":"",
    "STD":"",
    "Stealth":"",
    "Stealthing":"",
    "Stereotype":"",
    "Sterility":"",
    "Sterilization":"",
    "STI":"",
    "Stigma":"",
    "Stillbirth":"",
    "Straight":"",
    "Stranger rape":"",
    "Strap-on":"",
    "Strapless":"",
    "Structural racism":"",
    "Stud":"",
    "Stuffing":"",
    "Sudden Infant Death Syndrome":"",
    "Swinging":"",
    "Swyer syndrome":"",
    "Syphilis":"",
    "Systemic racism":"",
    "Taboo":"",
    "Tampon":"",
    "Temperature method":"",
    "Tenting":"",
    "Tertiary syphilis":"",
    "Testes":"",
    "Testicles":"",
    "Testosterone":"",
    "TGNCNB+":"",
    "The Health Insurance Portability and Accountability Act of 1996":"",
    "Thelarche":"",
    "Therapeutic abortion":"",
    "Third trimester":"",
    "Threatened miscarriage":"",
    "Thrush":"",
    "Tocophobia":"",
    "Top surgery":"",
    "Toxic shock syndrome":"",
    "Trans":"",
    "Trans mentor":"",
    "Transfeminine":"",
    "Transgender":"",
    "Transgender man / trans man":"",
    "Transgender woman / trans woman":"",
    "Transition":"",
    "Transmasculine":"",
    "Transphobia / transmisia":"",
    "Tribadism":"",
    "Trimester":"",
    "Triphasic combination pill":"",
    "Triple screen / triple test":"",
    "Tubal ligation":"",
    "Tubal pregnancy":"",
    "Tubal sterilization":"",
    "Tubectomy":"",
    "Tucking":"",
    "Tumescence":"",
    "Turner syndrome":"",
    "Two-day method":"",
    "Two-spirit / two spirit / 2S":"",
    "Typical use":"",
    "Tyson’s glands":"",
    "Ultrasound":"",
    "Uncircumcised":"",
    "Undescended testicle":"",
    "Unprotected sex":"",
    "Ureaplasma":"",
    "Ureters":"",
    "Urethra":"",
    "Urinary tract infection":"",
    "Uterine perforation":"",
    "Uterus":"",
    "UTI (urinary tract infection)":"",
    "Vacuum aspiration abortion":"",
    "Vagina":"",
    "Vaginal atrophy":"",
    "Vaginal contraceptive film / vcf":"",
    "Vaginal dilator":"",
    "Vaginal discharge":"",
    "Vaginal lubrication":"",
    "Vaginal orgasm":"",
    "Vaginal sex":"",
    "Vaginectomy":"",
    "Vaginismus":"",
    "Vaginitis":"",
    "Vaginoplasty":"",
    "Varicocele":"",
    "Vas deferens":"",
    "Vasectomy":"",
    "Vasocongestion":"",
    "Venereal disease (AKA VD)":"",
    "Viability":"",
    "Vibrator":"",
    "Victim-blaming":"",
    "Virginity":"",
    "Vocal surgery":"",
    "Voyeurism":"",
    "Vulva":"",
    "Wet dreams":"",
    "WIC":"",
    "Withdrawal":"",
    "XX chromosomes":"",
    "XY chromosomes":"",
    "Yeast infection":"",
    "Ze":"",
    "Zygote":"",

}